### ISSUE TITLE
`.github` automatic issues/PR management 

### ISSUE THREAD

**Issue by tsandrini** [tsandrini/practical-flakes-template#14]
## Description

It would be handy to have some sort of (**optional**) tool/action to automatically set the PR/issues labels from within the `.github` directory.

**Comment by tsandrini** [comment]
**Idea**: Maybe use `github-label-sync

```yaml
# .github/labels.yml
labels:
  - name: bug
    color: F00
    description: An issue with the system.
  - name: enhancement
    color: 0F0
    description: A new feature or improvement.
  - name: documentation
    color: 00F
    description: Improvements or additions to documentation.
```

and

```yaml
# .github/workflows/sync-labels.yml
name: "Sync Labels"
on:
  push:
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install github-label-sync
        run: npm install -g github-label-sync

      - name: Sync Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: github-label-sync --access-token $GITHUB_TOKEN --labels .github/labels.yml --allow-added-labels --repository ${{ github.repository }}
```
